# MYSQL LOCAL
spring.datasource.url=jdbc:mysql://localhost:3306/construplan
spring.datasource.username=root
spring.datasource.password=Matencios2805
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate 
#update