spring.application.name=construplan

# PUERTO

server.port=8080

# JPA

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# THYMELEAF

spring.thymeleaf.cache=false



spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima
