# MYSQL en Azure
spring.datasource.url=jdbc:mysql://construplan-db.mysql.database.azure.com:3306/construplan?sslMode=REQUIRED
spring.datasource.username=admin3a
# @construplan-db
spring.datasource.password=${mysql-password}
# Secreto en Key Vault
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate

# Key Vault
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=https://construplan-keyvalues.vault.azure.net/
